### ISSUE TITLE
how to interpret the result of METRO

### ISSUE THREAD

**Issue by arkyl** [zhengli09/METRO#2]
Hi,
Thanks much for the METRO package!
I am wondering how to interpret the METRO result, e.g alpha, weight and pvalueLRT.
For a simple linear association between one predicted gene expression and disease, one can get standard statistic such as beta, se and pval.
Here, the METRO uses multiple gene expressions and LRT so I am wondering if the results contain equivalent values to above beta or pval? is METRO alpha similar to the above beta? How should one interpret the weight; is the order of ethnicity in the weight the same as in the input expression list?

Thanks!

Yue

**Comment by zhengli09** [comment]
Hi Yue,
Thank you for your interest in METRO. Yes, the alpha parameter is equivalent to what you would call "beta" in a simple linear regression model. alpha = 0 indicates the GReX in none of the genetic ancestries has any effect on the trait. The order of genetic ancestry in the weight is indeed the same as the order in the input expression list. The weights are positive and sum to 1 and are interpreted as the contribution of the corresponding genetic ancestries in informing the GReX-trait association.
Best,
Zheng

**Comment by arkyl** [comment]
Thanks a lot for the explanation! That's exactly what i am asking. Please close the thread.
