### ISSUE TITLE
questions about METRO output

### ISSUE THREAD

**Issue by arkyl** [zhengli09/METRO#3]
Hi,
Thanks for your detailed reply in the previous thread.
I have a few questions about METRO output:

1. gamma ("A numeric scalar of horizontal pleiotropic effect"): we are planning to use METROEggerSumStat to account for horizontal pleiotropy. Do we need to set some practical cutoff on gamma, or the pvalueLRT from METROEggerSumStat is already controlled for horizontal pleiotropy?

2. h2m ("A numeric vector of cis-SNP heritabilities of gene expression in different genetic ancestries."): we are thinking about filtering genes by heritability significance, i.e pval of h2m. Is there such information available? or we may need to run other software to obtain it.

3. beta ("A numeric vector of genetic effects on gene expression among GWAS individuals."): Does this mean that by Sum(snp*beta), we will get the predicted expression. I noticed there is only one list of beta, regardless of gene expression ancestry. Is the beta most suitable or only suitable for individuals with LD structure similar to GWAS individuals, regardless of gene expression ancestry?

4. sigma2beta, sigma2m, sigma2: I don't quite understand these values. However, we are mainly interested in the final TWAS related values, so I ignored these values for now.

Thanks for your help with this!

Yue

**Comment by zhengli09** [comment]
Hi Yue,

Thank you for your questions! 

1. Yes, the p-value from METROEggerSumStat is after controlling for the horizontal pleiotropic effect.
2. Unfortunately, the current version of METRO does not provide any testing on heritabilities. You may refer to some commonly used softwares such as LDSC or MQS on that.
3. Yes, by doing X * beta, you would obtain the predicted gene expression values among GWAS individuals, where X is the genotype data in GWAS. It is calculated as a weighted summation of the genetic effects of different ancestries.
4. sigma2beta are variance parameters we assumed on beta, sigma2m are residual variance in models for gene expression data, and sigma2 is the residual variance in the model for GWAS data. You can refer to the "Overview of METRO" section of the paper for more details.

Hope these can help solve your questions. Please feel free to let me know if you have more questions!

Best,
Zheng

**Comment by arkyl** [comment]
Again thanks a lot for your explanations! It's very clear. Please close the issue.
