### ISSUE TITLE
Issue Opening PLTP_GEUVADIS,_S2.RData file

### ISSUE THREAD

**Issue by halkelchen** [zhengli09/METRO#5]
Hi,
I am having difficulty opening the data files provided for this package. I just want to see how the input data is formatted so that I can upload my GWAS summary data and gene expression data, but I keep getting a file/directory not found issue when trying to open it in Python, even when the path is correct. I tried using a browser which indicated the file might be zipped? Would you be able to help me figure this out!

**Comment by zhengli09** [comment]
Hi there,

Thank you for trying the package!  The example data can be accessed by typing "data(PLTP_GEUVADIS)" for individual-level input data or "data(PLTP_GEUVADIS_S2)" for summary-level input data in R. I am not quite sure about the equivalents of "data" function in python though. However, a workaround would be to load the data in R first and then write them out into text files. From there, you can load them into python. Hope this can be helpful.

Best,
Zheng

**Comment by halkelchen** [comment]
Hi,
I got it to work, must have just been an error with rpy2 when converting from python to the R interface. You can close this issue! Thanks for the quick response!
