### ISSUE TITLE
Issue installing the Package

### ISSUE THREAD

**Issue by halkelchen** [zhengli09/METRO#6]
Hi,
I am having difficulty installing the package. I keep receiving this error:
* checking for file ‘/private/var/folders/j3/cvvsq5352xn_1jkc5wh53c840000gn/T/RtmpTK0rR8/remotes1483410867c/zhengli09-METRO-bfdb5c5/DESCRIPTION’ ... OK
* preparing ‘METRO’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
  NB: this package now depends on R (>= 3.5.0)
  WARNING: Added dependency on R >= 3.5.0 because serialized objects in
  serialize/load version 3 cannot be read in older versions of R.
  File(s) containing such objects:
    ‘METRO/data/PLTP_GEUVADIS.RData’ ‘METRO/data/PLTP_GEUVADIS_S2.RData’
* building ‘METRO_1.0.tar.gz’

ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-METRO’
Downloading GitHub repo zhengli09/METRO@HEAD
In addition: Warning message:
In i.p(...) :
  installation of package ‘/var/folders/j3/cvvsq5352xn_1jkc5wh53c840000gn/T//RtmpTK0rR8/file148358ed38f9/METRO_1.0.tar.gz’ had non-zero exit status

When trying devtools::install_github("zhengli09/METRO")
None of the solutions I found online were able to fix this issue, unfortunately.

**Comment by zhengli09** [comment]
Hi there,

Thanks for your interest in our software! Do you want to follow the error message to remove the directory ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/00LOCK-METRO’ and then install the package again?

Best,
Zheng
